#!/bin/sh

for model in "./models"/*
do
  rm -rf ${model}/res/npy/*.npy
  rm -rf ${model}/res/prediction/*.png
  rm -rf ${model}/res/validation/*.png
  rm -rf ${model}/res/expired/*.png
  rm -rf ${model}/res/expired/*.npy
done
